DROP TABLE SOPORTE;
DROP TABLE MANTENIMIENTO;
DROP TABLE REPARACIONES;
DROP TABLE LINEAFACTURACOMPRA;
DROP TABLE LINEAFACTURAVENTA;
DROP TABLE FACTURASCOMPRA;
DROP TABLE FACTURASVENTATERMINAL;
DROP TABLE CONTRATOCLIENTE;
DROP TABLE TARIFAS;
DROP TABLE TRABAJADORES;
DROP TABLE TIPOSSOPORTES;
DROP TABLE PIEZASREPARACION;
DROP TABLE TERMINAL;
DROP TABLE PROVEEDORES;
DROP TABLE PUESTOSTRABAJO;
DROP TABLE TIENDA;
DROP TABLE CLIENTES;
DROP TABLE OPERADORES;

  CREATE TABLE  OPERADORES  
  (  IDOPERADOR  NUMBER(*,0), 
	 NOMBRE  VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ( IDOPERADOR )
  
   );

  CREATE TABLE  CLIENTES  
  (  TELEFONOMOVIL  NUMBER(*,0) NOT NULL ENABLE, 
	 EMAIL  VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 CUENTABANCARIA  NUMBER(*,0) NOT NULL ENABLE, 
	 NOMBRE  VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 APELLIDOS  VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 DNI  VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	 DIRECCION  VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ( DNI )
  
   );

  CREATE TABLE   TIENDA  
   (	 NOMBRE  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 UBICACION  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 TELEFONO  NUMBER NOT NULL ENABLE, 
	 EMAIL  VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 IDTIENDA  NUMBER (*,0)NOT NULL ENABLE, 
	 CONSTRAINT  TIENDA_PK  PRIMARY KEY ( IDTIENDA )
  
   ) ;

  CREATE TABLE   PUESTOSTRABAJO  
   (	 SUELDO  NUMBER NOT NULL ENABLE, 
	 FUNCION  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 NOMBRE  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 TIPOSTRABAJOS  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 IDPUESTO  NUMBER NOT NULL ENABLE, 
	 CONSTRAINT  PUESTOSTRABAJO_PK  PRIMARY KEY ( IDPUESTO )
    );

  
  CREATE TABLE   PROVEEDORES  
   (	 NOMBRE  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 APELLIDOS  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 DNI  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CIF  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT  PROVEEDORES_PK  PRIMARY KEY ( CIF )
  
   ) ;

  
  CREATE TABLE   TERMINAL  
   (	 MODELO  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 MARCA  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PANTALLA  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 TECLADO  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 MEMINTERNA  NUMBER NOT NULL ENABLE, 
	 MEMEXTERNA  NUMBER NOT NULL ENABLE, 
	 GPU  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CPU  NUMBER NOT NULL ENABLE, 
	 CAMARA  NUMBER NOT NULL ENABLE, 
	 CANTIDAD  NUMBER NOT NULL ENABLE, 
	 IDTERMINAL  NUMBER NOT NULL ENABLE, 
	 CONSTRAINT  TERMINAL_PK  PRIMARY KEY ( IDTERMINAL )
   
   ) ;

  CREATE TABLE   PIEZASREPARACION  
   (	 NOMBRE  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CANTIDADMATERIAL  NUMBER NOT NULL ENABLE, 
	 TERMINALASOCIADO  NUMBER NOT NULL ENABLE, 
	 IDPIEZA  NUMBER NOT NULL ENABLE, 
	 CONSTRAINT  PIEZASREPARACION_PK  PRIMARY KEY ( IDPIEZA ),
	 CONSTRAINT PIEZAS_MOVIL FOREIGN KEY (TERMINALASOCIADO)
	  REFERENCES TERMINAL (IDTERMINAL) ENABLE
   
   ) ;
   
   
   
   

  CREATE TABLE   TIPOSSOPORTES  
   (	 NOMBRE  VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 IDSOPORTES  NUMBER NOT NULL ENABLE, 
	 CONSTRAINT  TIPOSSOPORTES_PK  PRIMARY KEY ( IDSOPORTES )
    ) ;
	
	
	
		
	  CREATE TABLE  TRABAJADORES
	   (	NOMBRE VARCHAR2(25 BYTE), 
		APELLIDOS VARCHAR2(25 BYTE), 
		DNI VARCHAR2(20 BYTE) DEFAULT NULL NOT NULL ENABLE, 
		DIRECCION VARCHAR2(50 BYTE) DEFAULT NULL,
		TELEFONO NUMBER(*,0), 
		HORARIO VARCHAR2(25 BYTE), 
		FECHACONTRATO DATE, 
		IDTIENDA NUMBER NOT NULL ENABLE, 
		IDPUESTO NUMBER NOT NULL ENABLE, 
		 CONSTRAINT PKTRAB PRIMARY KEY (DNI), 
		 CONSTRAINT TRABAJADORES_PUESTOSTRABA_FK1 FOREIGN KEY (IDPUESTO)
		  REFERENCES  PUESTOSTRABAJO (IDPUESTO) ENABLE, 
		 CONSTRAINT TRABAJADORES_TIENDA_FK1 FOREIGN KEY (IDTIENDA)
		  REFERENCES  TIENDA (IDTIENDA) ENABLE
	   )
	 ;
	
	
 
  CREATE TABLE TARIFAS 
   (	IDTARIFA NUMBER(*,0), 
	PRECIOMINUTO NUMBER(4,2) NOT NULL ENABLE, 
	CONSUMOMINIMO NUMBER(4,3) NOT NULL ENABLE, 
	CUOTABASE NUMBER(4,3) NOT NULL ENABLE, 
	NMINUTOSGRATUITO NUMBER(4,0) NOT NULL ENABLE, 
	CUOTAINTERNET NUMBER(4,3) NOT NULL ENABLE, 
	NOMBRETARIFA VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	IDOPERADOR NUMBER (*,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDTARIFA),
	 CONSTRAINT TARIFAS_OPERADORES_FK1 FOREIGN KEY (IDOPERADOR)
	  REFERENCES OPERADORES (IDOPERADOR) ENABLE
   ) ;
   
   
  CREATE TABLE CONTRATOCLIENTE 
   (	FECHAINICIO DATE NOT NULL ENABLE, 
	FECHAFIN DATE NOT NULL ENABLE, 
	NUMEROTELEFONO NUMBER NOT NULL ENABLE, 
	IDCONTRATO NUMBER NOT NULL ENABLE, 
	IDTARIFA NUMBER NOT NULL ENABLE, 
	DNICLIENTE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	DNITRABAJADOR VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	IDTERMINAL NUMBER NOT NULL ENABLE, 
	 CONSTRAINT CONTRATOCLIENTE_PK PRIMARY KEY (IDCONTRATO),
	 CONSTRAINT CONTRATOCLIENTE_TERMINAL_FK1 FOREIGN KEY (IDTERMINAL)
	  REFERENCES TERMINAL (IDTERMINAL) ENABLE, 
	 CONSTRAINT CONTRATOCLIENTE_CLIENTES_FK1 FOREIGN KEY (DNICLIENTE)
	  REFERENCES CLIENTES (DNI) ENABLE, 
	 CONSTRAINT CONTRATOCLIENTE_TARIFAS_FK1 FOREIGN KEY (IDTARIFA)
	  REFERENCES TARIFAS (IDTARIFA) ENABLE, 
	 CONSTRAINT CONTRATOCLIENTE_TRABAJADO_FK1 FOREIGN KEY (DNITRABAJADOR)
	  REFERENCES TRABAJADORES (DNI) ENABLE
   );

   
    CREATE TABLE FACTURASVENTATERMINAL 
   (	CODFACTVENTA NUMBER NOT NULL ENABLE,  
	CODTRABAJADOR VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CODCLIENTE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT FACTURASVENTATERMINAL_PK PRIMARY KEY (CODFACTVENTA),
	 CONSTRAINT CLIENTEL_FK1 FOREIGN KEY (CODCLIENTE)
	  REFERENCES CLIENTES (DNI) ENABLE, 
	 CONSTRAINT TRABAJADOR_FK1 FOREIGN KEY (CODTRABAJADOR)
	  REFERENCES TRABAJADORES (DNI) ENABLE

	);
	
	 CREATE TABLE FACTURASCOMPRA 
   (
	 CODFACTCOMPRA NUMBER NOT NULL ENABLE, 
	CODPROVEEDOR VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CODTRABAJADOR VARCHAR2(20 BYTE), 
	 CONSTRAINT FACTURASCOMPRA_PK PRIMARY KEY (CODFACTCOMPRA),
	 CONSTRAINT PROVEEDOR_FK1 FOREIGN KEY (CODPROVEEDOR)
	  REFERENCES PROVEEDORES (CIF) ENABLE, 
	 FOREIGN KEY (CODTRABAJADOR)
	  REFERENCES TRABAJADORES (DNI) ENABLE
	);
   
   
  CREATE TABLE LINEAFACTURAVENTA 
   (	CONCEPTO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRECIO NUMBER NOT NULL ENABLE, 
	IDFACTURAVENTA NUMBER NOT NULL ENABLE, 
	IDTERMINAL NUMBER NOT NULL ENABLE, 
	IDLINEAFACTURAVENTA NUMBER NOT NULL ENABLE, 
	 CONSTRAINT LINEAFACTURAVENTA_PK PRIMARY KEY (IDFACTURAVENTA, IDLINEAFACTURAVENTA),
	 CONSTRAINT LINEAFACTURAVENTA_FACTURA_FK1 FOREIGN KEY (IDFACTURAVENTA)
	  REFERENCES FACTURASVENTATERMINAL (CODFACTVENTA) ENABLE, 
	 CONSTRAINT LINEAFACTURAVENTA_TERMINA_FK1 FOREIGN KEY (IDTERMINAL)
	  REFERENCES TERMINAL (IDTERMINAL) ENABLE
   ) ;
   
  CREATE TABLE LINEAFACTURACOMPRA 
   (	IDLINEAFACTURACOMPRA NUMBER NOT NULL ENABLE, 
	CONCEPTO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRECIOTOTAL NUMBER NOT NULL ENABLE, 
	FECHA DATE NOT NULL ENABLE, 
	IDFACTURACOMPRA NUMBER NOT NULL ENABLE, 
	IDPIEZA NUMBER, 
	IDTERMINAL NUMBER, 
	 CONSTRAINT LINEAFACTURACOMPRA_PK PRIMARY KEY (IDLINEAFACTURACOMPRA, IDFACTURACOMPRA),
	 CONSTRAINT LINEAFACTURACOMPRA_FACTUR_FK1 FOREIGN KEY (IDFACTURACOMPRA)
	  REFERENCES FACTURASCOMPRA (CODFACTCOMPRA) ENABLE, 
	 CONSTRAINT LINEAFACTURACOMPRA_PIEZAS_FK1 FOREIGN KEY (IDPIEZA)
	  REFERENCES PIEZASREPARACION (IDPIEZA) ENABLE, 
	 CONSTRAINT LINEAFACTURACOMPRA_TERMIN_FK1 FOREIGN KEY (IDTERMINAL)
	  REFERENCES TERMINAL (IDTERMINAL) ENABLE
   ) ;

   
  CREATE TABLE REPARACIONES
   (	IDREPARACION NUMBER NOT NULL ENABLE, 
	FECHAENTRADA DATE NOT NULL ENABLE, 
	FECHASALIDA DATE NOT NULL ENABLE, 
	IDTERMINAL NUMBER NOT NULL ENABLE, 
	REPARACIONESREALIZADAS VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	IDLINEAFACTURACOMP NUMBER NOT NULL ENABLE, 
	IDFACTURACOMPRA NUMBER NOT NULL ENABLE, 
	 CONSTRAINT REPARACIONES_PK PRIMARY KEY (IDREPARACION),
	 CONSTRAINT FACTURACOMPRA_FK1 FOREIGN KEY (IDFACTURACOMPRA)
	  REFERENCES FACTURASCOMPRA (CODFACTCOMPRA) ENABLE, 
	 CONSTRAINT LINEAFACTURACOMP_FK1 FOREIGN KEY (IDLINEAFACTURACOMP, IDFACTURACOMPRA)
	  REFERENCES LINEAFACTURACOMPRA (IDLINEAFACTURACOMPRA, IDFACTURACOMPRA) ENABLE
   ) ;

  
  CREATE TABLE MANTENIMIENTO 
   (	IDREPARACION NUMBER, 
	IDPIEZA NUMBER, 
	 CONSTRAINT MANTENIMIENTO_PIEZASREPAR_FK1 FOREIGN KEY (IDPIEZA)
	  REFERENCES PIEZASREPARACION (IDPIEZA) ENABLE, 
	 CONSTRAINT MANTENIMIENTO_REPARACIONES_FK1 FOREIGN KEY (IDREPARACION)
	  REFERENCES REPARACIONES (IDREPARACION) ENABLE
   ) ;

   

  CREATE TABLE SOPORTE 
   (	IDTERMINAL NUMBER, 
	IDTIPOSOPORTE NUMBER, 
	 CONSTRAINT SOPORTE_TERMINAL_FK1 FOREIGN KEY (IDTERMINAL)
	  REFERENCES TERMINAL (IDTERMINAL) ENABLE, 
	 CONSTRAINT SOPORTE_TIPOSSOPORTES_FK1 FOREIGN KEY (IDTIPOSOPORTE)
	  REFERENCES TIPOSSOPORTES (IDSOPORTES) ENABLE
   );
  
  
  
  --TRIGGERS
  
  create or replace trigger fechasReparacion
  BEFORE UPDATE OF fechaSalida ON Reparaciones
  FOR EACH ROW

BEGIN
  IF(:NEW.fechasalida < :OLD.fechaentrada)
    THEN raise_application_error(-20600,:NEW.fechasalida ||'La fecha de salida no puede ser anterior a la fecha de entrada');
  END IF;
END;



create or replace trigger pedidos
  BEFORE INSERT OR UPDATE OF cantidad ON TERMINAL
  FOR EACH ROW

DECLARE
  --cant INTEGER;
BEGIN
  --SELECT cantidad INTO cant FROM TERMINAL;
  IF(:NEW.cantidad < 5)
    THEN raise_application_error(-20600,:NEW.cantidad||'Debemos pedir mas terminales a los proveedores');
  END IF;
END;

create or replace trigger PEDIDOSPIEZAS 
BEFORE INSERT OR UPDATE OF cantidadMaterial ON PIEZASREPARACION 
 FOR EACH ROW

--DECLARE
--  cant INTEGER;
BEGIN
  --SELECT cantidadMaterial INTO cant FROM PIEZASREPARACION;
  IF(:NEW.cantidadMaterial < 5)
    THEN raise_application_error(-20600,:NEW.cantidadMaterial||'Debemos pedir mas materiales a los proveedores');
  END IF;
END;
----FUNCIONES
CREATE OR REPLACE FUNCTION salario--sacar el salario del empleado
(IDEMPLEADO IN VARCHAR2 (25 BYTE))
RETURN NUMBER
IS idsueldo PUESTOTRABAJO.SUELDO%TYPE;
BEGIN 
SELECT sueldo INTO idsueldo
FROM PUESTOTRABAJO
WHERE IDPUESTO = IDEMPLEADO;
RETURN idsueldo;
END salario;

--procedures---


CREATE OR REPLACE PROCEDURE contratoempleado
(IDDNI IN TRABAJADORES.DNI%TYPE,
IDFECHACONTRATO IN TRABAJADORES.FECHACONTRATO%TYPE) 
 IS
 BEGIN 
INSERT INTO TRABAJADORES(DNI, FECHACONTRATO)
VALUES (IDDNI, IDFECHACONTRATO);
END contratoempleado;

--cursores--

DECLARE
	CURSOR cursor_1 IS
	SELECT sueldo, funcion, nombre, tipostrabajos, idpuesto
	FROM PUESTOSTRABAJO ORDER BY sueldo;
	w_sueldo	PUESTOSTRABAJO.sueldo%TYPE;
	w_funcion	PUESTOSTRABAJO.funcion%TYPE;
	w_nombre	PUESTOSTRABAJO.nombre%TYPE;
	w_tipostrabajos	PUESTOSTRABAJO.tipostrabajos%TYPE;
	w_idpuesto	PUESTOSTRABAJO.idpuesto%TYPE;
BEGIN
	OPEN cursor_1;
	FETCH cursor_1 INTO w_sueldo, w_funcion, w_nombre, w_tipostrabajos, w_idpuesto;
	CLOSE cursor_1;
END;

--inserts--

insert into OPERADORES (IDOPERADOR, nombre) values ('001','yoigo');
insert into OPERADORES (IDOPERADOR, nombre) values ('002','movistar');

insert into CLIENTES (dni,telefonoMovil,email,cuentaBancaria,nombre,apellidos,direccion) values ('01024561J','654632178','felix@gmail.com','025821256854233695','Sara','Perez Pi�a','Calle el puerto , n� 4');
insert into CLIENTES (dni,telefonoMovil,email,cuentaBancaria,nombre,apellidos,direccion) values ('78954231A','686592178','maria89@gmail.com','025821259658433695','Francisco','Castro Pinz�n','Calle el compas, n� 7');

insert into TIENDA (IDTIENDA,nombre,ubicacion,telefono,email) values (0,'Nomb0','C/A n�1','954673817','calleA@gmail.com');
insert into TIENDA (IDTIENDA,nombre,ubicacion,telefono,email) values (1,'Nomb1','Avenida Bn�2','975263718','calleB@gmail.com');

insert into PUESTOSTRABAJO (idpuesto,sueldo,funcion,nombre,tiposTrabajos) values (0,758.00,'revisiones','Manuel','tecnico');
insert into PUESTOSTRABAJO (idpuesto,sueldo,funcion,nombre,tiposTrabajos) values (1,816.00,'administrativa','Rosa','asistente');

insert into PROVEEDORES (nombre,apellidos,dni,cif) values ('Carlos','P�rez D�az','30284314D','12345678A');
insert into PROVEEDORES (nombre,apellidos,dni,cif) values ('David','�lvarez Castro','48852773G','34567890B');

insert into TERMINAL (idterminal,marca,modelo,pantalla,teclado,memInterna,memExterna,gpu,cpu,camara,cantidad) values (0,'samsung','GalaxyS3','480x800','tactil',512,4,'Adreno200',800,8,8);
insert into TERMINAL (idterminal,marca,modelo,pantalla,teclado,memInterna,memExterna,gpu,cpu,camara,cantidad) values (1,'sorny','XPERIAARCS','240x320','tactil',1024,8,'Adreno200',800,8,7);

insert into PIEZASREPARACION (idpieza,nombre,cantidadMaterial,terminalAsociado) values (0,'pantalla','2',0);
insert into PIEZASREPARACION (idpieza,nombre,cantidadMaterial,terminalAsociado) values (1,'teclado','2',1);

insert into TIPOSSOPORTES (IDSOPORTES,nombre) values (0,'JPG');
insert into TIPOSSOPORTES (IDSOPORTES,nombre) values (1,'AVI');

insert into TRABAJADORES (dni,IDTIENDA,idpuesto,telefono,horario,fechaContrato,nombre,apellidos,direccion) values ('6666667D',0,0,666666665,'10:00-14:00',to_date('2008/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),'Lance','Hardwood','calle falsa 123');
insert into TRABAJADORES (dni,IDTIENDA,idpuesto,telefono,horario,fechaContrato,nombre,apellidos,direccion) values ('6666668D',1,1,666666666,'9:00-12:00',to_date('2009/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),'Ristro','Montoya','calle falsa 122');

insert into TARIFAS (idtarifa,precioMinuto,consumoMinimo,cuotaBase,NMINUTOSGRATUITO,cuotaInternet,nombreTarifa,IDOPERADOR) values (0,6,5,0,0,0,'S',001);
insert into TARIFAS (idtarifa,precioMinuto,consumoMinimo,cuotaBase,NMINUTOSGRATUITO,cuotaInternet,nombreTarifa,IDOPERADOR) values (1,5,1,6,0,0,'M',002);

insert into CONTRATOCLIENTE (FECHAINICIO,FECHAFIN,NUMEROTELEFONO,IDCONTRATO,IDTARIFA,DNICLIENTE,DNITRABAJADOR,IDTERMINAL) values (to_date('2008/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),to_date('2024/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),955612233,0,0,'01024561J','6666667D',1);
insert into CONTRATOCLIENTE (FECHAINICIO,FECHAFIN,NUMEROTELEFONO,IDCONTRATO,IDTARIFA,DNICLIENTE,DNITRABAJADOR,IDTERMINAL) values (to_date('2009/06/21 10:48:05', 'yyyy/mm/dd hh24:mi:ss'),to_date('2014/06/21 10:48:05', 'yyyy/mm/dd hh24:mi:ss'),666666666,1,1,'78954231A','6666668D',0);

insert into FACTURASVENTATERMINAL(CODFACTVENTA,CODTRABAJADOR,CODCLIENTE) values(0,'6666667D','01024561J');
insert into FACTURASVENTATERMINAL(CODFACTVENTA,CODTRABAJADOR,CODCLIENTE) values(1,'6666668D','78954231A');

insert into FACTURASCOMPRA(CODFACTCOMPRA,CODPROVEEDOR,CODTRABAJADOR) values(0,'12345678A','6666667D');
insert into FACTURASCOMPRA(CODFACTCOMPRA,CODPROVEEDOR,CODTRABAJADOR) values(1,'12345678A','6666668D');

insert into LINEAFACTURAVENTA(CONCEPTO,PRECIO,IDFACTURAVENTA,IDTERMINAL,IDLINEAFACTURAVENTA) values('Compra de gs3',500,0,0,0);
insert into LINEAFACTURAVENTA(CONCEPTO,PRECIO,IDFACTURAVENTA,IDTERMINAL,IDLINEAFACTURAVENTA) values('Compra de htc One',450,1,1,1);

insert into LINEAFACTURACOMPRA(IDLINEAFACTURACOMPRA,CONCEPTO,PRECIOTOTAL,FECHA,IDFACTURACOMPRA,IDPIEZA,IDTERMINAL) values(0,'Compra terminales',600,to_date('2008/05/03 21:02:44','yyyy/mm/dd hh24:mi:ss'),0,0,0);
insert into LINEAFACTURACOMPRA(IDLINEAFACTURACOMPRA,CONCEPTO,PRECIOTOTAL,FECHA,IDFACTURACOMPRA,IDPIEZA,IDTERMINAL) values(1,'Compra terminales',800,to_date('2009/06/21 10:48:05','yyyy/mm/dd hh24:mi:ss'),1,1,1);

insert into REPARACIONES(IDREPARACION,FECHAENTRADA,FECHASALIDA,IDTERMINAL,REPARACIONESREALIZADAS,IDLINEAFACTURACOMP,IDFACTURACOMPRA) values(0,to_date('2008/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),to_date('2008/05/28 10:00:00','yyyy/mm/dd hh24:mi:ss'),0,'Cambio de la pantalla',0,0);
insert into REPARACIONES(IDREPARACION,FECHAENTRADA,FECHASALIDA,IDTERMINAL,REPARACIONESREALIZADAS,IDLINEAFACTURACOMP,IDFACTURACOMPRA) values(1,to_date('2013/06/12 14:35:00', 'yyyy/mm/dd hh24:mi:ss'),to_date('2013/07/12 18:00:00','yyyy/mm/dd hh24:mi:ss'),1,'Cambio del teclado',1,1);

insert into MANTENIMIENTO(IDREPARACION,IDPIEZA) values(0,0);
insert into MANTENIMIENTO(IDREPARACION,IDPIEZA) values(1,1);

insert into SOPORTE(IDTERMINAL,IDTIPOSOPORTE) values(0,0);
insert into SOPORTE(IDTERMINAL,IDTIPOSOPORTE) values(1,1);


CREATE SEQUENCE terminales--secuencia para poder definir la primary key . añadido antes del commit.
  Start With 2
  Increment By 1
  CACHE 10;



--script de prueba--
UPDATE REPARACIONES
SET FECHAENTRADA=to_date('2009/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'),FECHASALIDA=to_date('2008/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss');

UPDATE TERMINAL
SET CANTIDAD=3
WHERE IDTERMINAL=0;

UPDATE PIEZASREPARACION
SET CANTIDADMATERIAL=3
WHERE IDPIEZA = 0;